language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest
script:
  - cd task2/
  
  - 2to3 -w test_2.py  

  - py.test test_2.py
  
  - py.test test_3.py
